### ISSUE TITLE
Please error ( File "fix_db.py", line 69, in <module> ftp.connect(PS4_IP, port, timeout=30)

### ISSUE THREAD

**Issue by ToniFabri** [aizenar/PS4_db_Rebuilder_EXT#13]
i have this problem i followed all the steps correctly

version 9.00, goldhein 2.2.1
windows 7
python-3.8.10

logs : 
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. Todos os direitos reservados.

PS C:\Users\s11\Desktop\PS4_db_Rebuilder_EXT-0.1> py fix_db.py 10.0.0.145
Traceback (most recent call last):
  File "fix_db.py", line 69, in <module>
    ftp.connect(PS4_IP, port, timeout=30)
  File "C:\Users\s11\AppData\Local\Programs\Python\Python38-32\lib\ftplib.py", l
ine 154, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout,
  File "C:\Users\s11\AppData\Local\Programs\Python\Python38-32\lib\socket.py", l
ine 808, in create_connection
    raise err
  File "C:\Users\s11\AppData\Local\Programs\Python\Python38-32\lib\socket.py", l
ine 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Nenhuma conexão pôde ser feita porque a
 máquina de destino as recusou ativamente
PS C:\Users\s11\Desktop\PS4_db_Rebuilder_EXT-0.1>

**Comment by plato79** [comment]
Are you sure that you enabled FTP server in GoldHen? It seems it cannot connect to the FTP server.

**Comment by ToniFabri** [comment]
Ok solve my problem , FTP off, thanks

**Comment by ih81o** [comment]
i have this problem i followed all the steps correctly

version 9.00, goldhein 2.2.1
windows 10
python-3.8.10

C:\Users\Mani\Desktop\PS4_db_rebuilder-master» py fix_db.py 192.168.100.36 Traceback (most recent call last): GA File "fix_db.py", line 51, in <module> ftp.connect (PS4 IP, 1337, timeout=30) File "C:\Users\Hani\AppData\Local\Programs\Python\Python38\lib\ftplib.py", line 154, in connect self.sock socket.create_connection((self host, self.port), self.timeout, le "c:\Users\Mani\AppData\Local\Programs\Python Python38\116\socket.py". 1ine sos, in create connection raise err File C:\Users\Mani\AppData\Local\Programs\Python\Python38\lib\socket.py", line 796, in create_connection sock.connect (sa) ConnectionRefusedError: [winError 10061] No connection could be made because the target machine actively refused it

**Comment by plato79** [comment]
Either your IP is wrong or you didn't enable FTP in GoldHEN settings...

**Comment by ih81o** [comment]
> Either your IP is wrong or you didn't enable FTP in GoldHEN settings...

I checked my ip multiple time and enable FTP !
And I even try to send a game to my ps4 and it'work but when i try to run the script doesn't work !

**Comment by plato79** [comment]
Sending game requirements are different. You can send a game with FTP disabled.
Your FTP port is 2121 right? Can you connect it through an FTP client? If there is none, you could also test it via `telnet <ps4_ip> 2121` command. Although you need to have telnet client installed on Windows features.

**Comment by wankio** [comment]
edit fix_db.py, change 2121 to 1337 or any port number showed when u active FTP
